import Head from 'next/head'
import Header from '../components/header/Header'
import Logo from '../components/reusebleComponents/logo/Logo'
// import Logo from '../components/reusebleComponents/Logo'
import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div className={styles.home}>
      <Head>
        <title>Phare web</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>

      <Logo/>
     
    </div>
  )
}
