import Head from 'next/head'
import Header from '../components/header/Header'
import Logo from '../components/logo/Logo'
// import Logo from '../components/reusebleComponents/logo/Logo'
// import Logo from '../components/reusebleComponents/Logo'
import styles from '../styles/Home.module.scss'
1
// import 'bootstrap/dist/css/bootstrap.min.css';
// import 'bootstrap/dist/css/bootstrap.min.css';
//should through an error on push
export default function Home() {
  return (
    <div className={styles.home}>
      <Head>
        <title>Phare web</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <script src="https:code.jquery.com/jquery-3.4.1min.js"/> */}
      </Head>
      <Header />

      <Logo />
    </div>
  )
}
