name: CI
on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]
jobs:
  build:
   runs-on: self-hosted
   strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node-version:
          - 14
          - 16
          - 17
        architecture:
          - x64
          - arm64
   steps:
     - uses: actions/checkout@v3
     - name: Use NodeJs
       uses: actions/setup-node@v3
       with:
         node-version: ${{ matrix.node-version }}
         cache: 'npm'
     - run: npm ci # ci is replace of install, and it's recomended
     - run: npm run code:check
     - name: Build Project
       if: github.event_name == 'push'
       run: npm run build --if-present
        # tests sections goes here
    #  - run: npm test -- --coverage
    #    env:
    #      CI: true
       
      