name: CI
on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]
jobs:
  build:
   runs-on: self-hosted
   steps:
     - uses: actions/checkout@v2
     - name: Use NodeJS
       uses: actions/setup-node@v1
       with:
         node-version: '12x'
     - run: npm ci
     - run: npm run code:check