name: CI
on:
  pull_request:
    branches: [develop]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - run: npm ci   #install
      - run: npm code:check
        # run tests if you have
      # - run: npm test -- --coverage
      #   env:
      #     CI: true
        
    