name: CI
on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - name: Use NodeJs
       uses: actions/setup-node@v2
       with:
         node-version: '16x'
     - run: npm ci # ci is replace of install, and it's recomended
     - run: npm run code:check
        # tests sections goes here
    #  - run: npm test -- --coverage
    #    env:
    #      CI: true
       
      