name: CI
on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]
jobs:
  build:
   runs-on: ubuntu-latest 
   strategy:
     matrix:
       node-version: [16.x]
   steps:
     - uses: actions/checkout@v2
     - name: Use NodeJS
       uses: actions/setup-node@v3
       with:
         node-version: ${{ matrix.node-version }}
     - run: npm ci
     - run: npm run code:check
     - name: Build Project
       if: github.event_name == 'push'
       run: npm run build
     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
         aws-access-key-id: AKIA4IPKHFOEDL3CSQE2
         aws-secret-access-key: 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
         aws-region:  eu-central-1 #us-east-1
     - name: Copy files to the staging website with the AWS CLI
       run: |
        aws s3 sync out/ s3://phare-web



