name: CI
on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]
jobs:
  build:
   runs-on: ubuntu-latest
   strategy:
     matrix:
       node-version: [16.x]
   steps:
     - uses: actions/checkout@v2
     - name: Use NodeJS
       uses: actions/setup-node@v3
       with:
         node-version: ${{ matrix.node-version }}
     - run: npm ci
     - run: npm run code:check
     - name: Build Project
       if: github.event_name == 'push'
       run: npm run build
     - name: Configure AWS credentials
     - uses: aws-actions/configure-aws-credentials@v1
       with:
         aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
         aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
         aws-region: eu-central-1
     - name: Copy files to the production website with the AWS CLI
       run: |
        aws s3 sync ./out s3://phare-web
         