name: Pipeline
on:
  push:
    branches:
      - main
jobs:
  # lintTest:
  #   name: Lint
    # runs-on: ubuntu-latest
    # steps:
    #   - name: Clone Repo
    #     uses: actions/checkout@v2
    #   - name: Installing Dependencies
    #     run: |
    #       echo "Running installing dependencies"
    #       npm install
    #   - name: Run linting
    #     run: |
    #       echo "Running linting tests"
    #       npm run lint
    #     env:
    #       CI: true
  securityCheck:
    name: Security-Check
    runs-on: ubuntu-latest
    steps:
      - name: chcek for security
        run: |
          echo "run security checks"
          sleep 5s;
          echo "run security checks..1"
          sleep 5s;
          echo "run security checks..2"
          sleep 5s;
          echo "run security checks..3"
          sleep 5s;
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    needs: [securityCheck]
    steps:
      - name: chcek for security
        run: |
          echo "Deployment in progress"

       

